# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example_password
      POSTGRES_USER: root
      POSTGRES_DB: ecommerce_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
